### ISSUE TITLE
help wanted: How to add and remove menu items for the SideNav menu.

### ISSUE THREAD

**Issue by alisadeghi88** [creativetimofficial/ct-soft-ui-dashboard-pro-react#10]
I have been trying for days. I have asked this question and never got it answer. Please help me. how do i add and remove menu items from the SideNav. Please don't ask me to clarify because this is an easy one to understand. I have asked many questions none have been answered. this is the easy way i know how to explain it . Please help me. payed for all your products at least answer this one question.

**Comment by sajadevo** [comment]
**Hi Ali**

Thanks for using our product, sorry for the late reply we're just a bit busy with the new plans for our products.
To add or remove menu items from Sidenav is simple and easy you can just do it by editing the routes.js file each item has a name icon an key in a form of object if you want to remove it remove the object related to the item you want and if you want to add one duplicate that object and edit it the way you want. On the top of the routes.js file I've explained every key and their task.

**All the best
Sajad**
