### ISSUE TITLE
React dependency issues

### ISSUE THREAD

**Issue by shawncutter** [creativetimofficial/ct-soft-ui-dashboard-pro-react#11]
I am getting a lot of dependency issues with a lot of the react packages.  Is there an easy button for updating these?

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm ERR! node_modules/react-html-parser
npm ERR!   react-html-parser@"2.0.2" from the root project
npm ERR!

**Comment by sajadevo** [comment]
**Hi @shawncutter **

Thanks for using our products, please take it easy there warning and errors won't affect on the behavior of the app, but we will update them on the next update of the product.
If this error causing to interrupt the installation and running the product, please lemme know I will provide you a quick fix.

**All the best**
**Sajad**

**Comment by mxnr** [comment]
Same for me, @shawncutter when do you guys plan to make a new release? Thanks!

**Comment by sajadevo** [comment]
**Hi @shawncutter **

Thanks for using the product, we will have a new of the product with-in a month.

**All the best
Sajad**

**Comment by josiahbryan** [comment]
Can you ping this thread when the release drops? And release are included with the purchase for X months, yes...?

**Comment by dragosct10** [comment]
Hi, @josiahbryan! Here on [discord](https://discord.gg/FhCJCaHdQa) we post all the updates and releases and here you can see the updates in real time. 

Regards,
Dragos
