### ISSUE TITLE
react+laravel

### ISSUE THREAD

**Issue by dguptahellohello** [creativetimofficial/ct-soft-ui-dashboard-pro-react#12]
i use soft-ui-dashboard-pro-react
SuiSelect components  not work my laravel api
plz help

**Comment by sajadevo** [comment]
**Hi @dguptahellohello **

Thanks for using our product, please check your console and give me more details of why its not working and I will assist you.

Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad
