### ISSUE TITLE
[Bug] Failed to parse source map from 'C:\Users\jose\Downloads\minumeapp-front\node_modules\@pathofdev\react-tag-input\build\index.css.map'

### ISSUE THREAD

**Issue by joseangelhernandez** [creativetimofficial/ct-soft-ui-dashboard-pro-react#13]
### Version
3.0.0
### Reproduction link
http://localhost:3000/soft-ui-dashboard-pro-react
### Operating System
Windows 11
### Device
PC
### Browser & Version
Microsoft Edge  98.0.1108.50
### Steps to reproduce
I installed all NPM
### What is expected?
The page keep empty
### What is actually happening?
WARNING in ./node_modules/@pathofdev/react-tag-input/build/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/@pathofdev/react-tag-input/build/index.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\jose\Downloads\minumeapp-front\node_modules\@pathofdev\react-tag-input\build\index.css.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\jose\Downloads\minumeapp-front\node_modules\@pathofdev\react-tag-input\build\index.css.map'
 @ ./node_modules/@pathofdev/react-tag-input/build/index.css 8:6-241 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-211 83:0-211 84:22-29 84:33-47 84:50-64 61:4-74:5   
 @ ./src/components/SuiTagInput/index.js 24:0-52
 @ ./src/layouts/pages/account/settings/components/BasicInfo/index.js 28:0-49 372:43-54
 @ ./src/layouts/pages/account/settings/index.js 27:0-76 80:47-56
 @ ./src/routes.js 53:0-54 206:17-25
 @ ./src/App.js 38:0-28 154:16-22 171:27-33
 @ ./src/index.js 22:0-22 28:35-38

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.69.0 compiled with 1 warning in 2873 ms

---

**Comment by joseangelhernandez** [comment]
I resolved that errors now I have this error
Failed to load config "react-app" to extend from.
Referenced from: C:\Users\jose\Downloads\package.json

**Comment by sajadevo** [comment]
**Hi @joseangelhernandez **

Thanks for using our product, for a quick fix please remove the following part from the package.json file:

```
"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
},
```

Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad
