### ISSUE TITLE
[Bug] Failed to compile + page displays an iframe where I can't click anything

### ISSUE THREAD

**Issue by MBWebTechMariusz** [creativetimofficial/ct-soft-ui-dashboard-pro-react#14]
### Version
3.0.0
### Reproduction link
https://www.creative-tim.com/learning-lab/material-ui-marketplace/quick-start/soft-ui-dashboard/
### Operating System
MacOS 12.2.1
### Device
MacBook Pro
### Browser & Version
Google Chrome 98.0.4758.102 
### Steps to reproduce
1. yarn install
2. yarn start
### What is expected?
https://demos.creative-tim.com/soft-ui-dashboard-pro-react/marketplace/#/dashboards/default
### What is actually happening?
Failed to compile.

Failed to load config "react-app" to extend from.
Referenced from: /...../package.json

http://localhost:3000/dashboards/default opens, but it is an iframe and I can't click on any elements.

---
### Additional comments
I've bought the PRO version. Order nr. #37889

**Comment by sajadevo** [comment]
**Hi @MBWebTechMariusz **

Thanks for using our product, could you please put your project into a private repo and invite me so that I can check it.

Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad

**Comment by sajadevo** [comment]
**Hi @MBWebTechMariusz **

Thanks for using our product, for a quick fix please remove the following part from the package.json file:

"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
},
Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad
