### ISSUE TITLE
[Bug] Unable to pass the prop step="any" into <SuiInput type="number"/>

### ISSUE THREAD

**Issue by yampan79** [creativetimofficial/ct-soft-ui-dashboard-pro-react#15]
### Version
3.0.0
### Reproduction link
http://www.noexample.provided
### Operating System
MacOS & iOS
### Device
MacBook, iPhone & iPad
### Browser & Version
latest version
### Steps to reproduce
<form onSubmit{(e) => e.preventDefault}>
    <input type="number" step="any">
    <SuiInput id="id" name="name"  type="number" step="any"/>
    <button type="submit">Submit</button>
</form>

1. Enter a decimal number (e.g. 12.8) in both fields.
2. The input tag will pass HTML validation
3. The SuiInput will fail HTML validation
### What is expected?
In Safari, it's not possible to input a decimal number into <input type="number"> due to HTML validation. 

To accept a decimal in the input field, the workaround is to pass a prop of step="any" into the input tag 

<input type="number" step="any">

### What is actually happening?
However, the SuiInput component does not pass down the prop step="any" 

<SuiInput id="id" name="name"  type="number" step="any"/> does not allow decimal in Mac Safari

---
### Solution
Hi, my name is Yan and I purchase the React Bundle recently.

Please let me know how can I pass the prop step= "any" in the SuiInput component. Thanks!

**Comment by sajadevo** [comment]
**Hi #yampan79 **

Thanks for using our product, please use the `<SuiInput inputProps={{ step: "any" }} />`.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad**
