### ISSUE TITLE
Prop type "any", "object", "array" are forbidden

### ISSUE THREAD

**Issue by Abiram-N** [creativetimofficial/ct-soft-ui-dashboard-pro-react#16]
### Issue when Reinstalling Project  
We are facing this issue starting from 26 FEB 2022 SATURDAY. When we try to reinstall the project with `npm install` and `npm start` (Fresh Install). 

    Failed to compile.
    
    src/components/SuiDatePicker/index.js
      Line 46:3:  Prop type "any" is forbidden  react/forbid-prop-types
    
    src/components/SuiDropzone/index.js
      Line 68:3:  Prop type "any" is forbidden  react/forbid-prop-types
    
    src/examples/Cards/EventCard/index.js
      Line 134:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Cards/InfoCards/ProfileInfoCard/index.js
      Line 127:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Cards/PricingCards/DefaultPricingCard/index.js
      Line 132:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Cards/ProjectCards/DefaultProjectCard/index.js
      Line 175:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Cards/TeamCards/TeamProfileCard/index.js
      Line 229:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/BarCharts/HorizontalBarChart/index.js
      Line 96:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/BarCharts/VerticalBarChart/index.js
      Line 96:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/BubbleChart/index.js
      Line 98:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/LineCharts/DefaultLineChart/index.js
      Line 98:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/LineCharts/GradientLineChart/index.js
      Line 109:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/LineCharts/ProgressLineChart/index.js
      Line 107:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/MixedChart/index.js
      Line 167:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Charts/RadarChart/index.js
      Line 92:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Lists/CategoriesList/index.js
      Line 116:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Lists/ProfilesList/index.js
      Line 85:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/DefaultNavbarMobile.js
      Line 113:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/Menus/ApplicationsMenu.js
      Line 88:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/Menus/AuthenticationMenu.js
      Line 187:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/Menus/DocsMenu.js
      Line 78:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/Menus/EcommerceMenu.js
      Line 94:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/Menus/PagesMenu.js
      Line 106:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Navbars/DefaultNavbar/index.js
      Line 221:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Sidenav/index.js
      Line 259:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Tables/DataTable/index.js
      Line 282:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/examples/Tables/SalesTable/index.js
      Line 88:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/examples/Tables/Table/index.js
      Line 155:3:  Prop type "object" is forbidden  react/forbid-prop-types
      Line 156:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/layouts/account/components/SecureBox/components/DeviceCard/index.js
      Line 173:3:  Prop type "object" is forbidden  react/forbid-prop-types
    
    src/layouts/dashboard/components/LineCharts/DefaultLineChart/index.js
      Line 98:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/layouts/pages/rtl/components/Chart/index.js
      Line 97:3:  Prop type "array" is forbidden  react/forbid-prop-types
    
    src/layouts/pages/widgets/components/Chart/index.js
      Line 97:3:  Prop type "array" is forbidden  react/forbid-prop-types

The Issue is related to prop-types package a library for typechecking of props. The below three prop type are flagged as forbidden by  react/forbid-prop-types

 1. Any (PropTypes.any) 
 2. Object (PropTypes.object) 
 3. Array (PropTypes.Array)

**Comment by Abiram-N** [comment]
### **The Below Reference is from eslint-plugin-react**
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

**Fix we applied for this Issue**

Replace

> PropTypes.array to Array
> PropTypes.object to Object

After Replacing the code looks like this

```
PropTypes.arrayOf(Object) // From src/examples/Cards/EventCard/index.js
PropTypes.objectOf(Array).isRequired // from src/examples/Charts/BarCharts/HorizontalBarChart/index.js
```

Likewise replace all the occurrence of PropTypes.array and PropTypes.object to Array and Object Respectively.



**

## The conversion of `PropTypes.any`  need to be evaluated

**

**src/components/SuiDatePicker/index.js**

    // Typechecking props for the SuiDatePicker
    SuiDatePicker.propTypes = {
	    input:  PropTypes.objectOf(Object),
    };
       
              
 **src/components/SuiDropzone/index.js**

    // Typechecking props for the SuiDropzone
    SuiDropzone.propTypes = {
      options: PropTypes.objectOf(Array).isRequired,
    };

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product dependencies and dev-dependencies and it seems that the issue is fix on the new update.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad**
