### ISSUE TITLE
[Bug] .eslint.json .prettierrc.json not included in package

### ISSUE THREAD

**Issue by goff-studio** [creativetimofficial/ct-soft-ui-dashboard-pro-react#2]
### Version
2.0.0
### Operating System
MacOS
### Device
Macbook Air m1
### Browser & Version
not applicable
### Steps to reproduce
download the project
unzip via terminal or finder
### What is expected?
to find eslint and prettier rules and configurations [in the readme file you mentioned that they are included]
### What is actually happening?
eslint and prettier not included in the downloaded package

---

**Comment by sajadevo** [comment]
**Hi @goff-studio **
Thanks for using our products, the .eslint.json .prettierrc.json files are already included inside the package but these file are hidden and only visible inside your code editor (vs-code).

**All the best**
**Sajad**
