### ISSUE TITLE
Data table

### ISSUE THREAD

**Issue by rodevandroid** [creativetimofficial/ct-soft-ui-dashboard-pro-react#23]
How set hover row efect in data table body ?

**Comment by sajadevo** [comment]
**Hi @rodevandroid**

Thanks for using our product, DataTable is using [React Table](https://react-table.tanstack.com/) behind the sense and you can use it as reference on how to add the hover effect for rows.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by rodevandroid** [comment]
tks brow
