### ISSUE TITLE
[Bug] ERROR in Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig

### ISSUE THREAD

**Issue by lagrawal1313** [creativetimofficial/ct-soft-ui-dashboard-pro-react#24]
### Version
eslint Version is 10
### Reproduction link
https://www.creative-tim.com/product/soft-ui-dashboard-pro-react
### Operating System
Windows
### Device
Windows
### Browser & Version
Chrome
### Steps to reproduce
issue when starting the server
### What is expected?
the server should start
### What is actually happening?
process is termianted

---

**Comment by lagrawal1313** [comment]
Hello,
any updates?

**Comment by sajadevo** [comment]
**Hi @lagrawal1313**

Please create a file named `.yarnrc.yml` and put the following code inside of it `pnpFallbackMode: all`.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by minhChien98** [comment]
@sajadevo  
i have tried to do like that. But the result is still not good

**Comment by sajadevo** [comment]
**Hi @minhChien98**

Tomorrow I'll release an update for the product and this issue will be fixed.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by hall2000C** [comment]
> **Hi @lagrawal1313**
> 
> Please create a file named `.yarnrc.yml` and put the following code inside of it `pnpFallbackMode: all`.
> 
> **Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**
> 
> **All the best, Sajad  React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

Hi there , this issue is not solved with 4.0 but your solution worked.

**Comment by kvjoshi** [comment]
this is still causing an issue . tried adding pnpfallbackmode:all to .yarnrc

**Comment by abhi3566** [comment]
still facing this issue
