### ISSUE TITLE
react-github-btn

### ISSUE THREAD

**Issue by hall2000C** [creativetimofficial/ct-soft-ui-dashboard-pro-react#25]
Hy guys I have this problem when compiling : 

ERROR in ./src/examples/Configurator/index.js 22:0-44

Module not found: Error: Can't resolve 'react-github-btn' in '/Users/cristian/Desktop/NFTIM/soft-ui-dashboard-pro-react-v4.0.0/src/examples/Configurator'

What should I do?

Thank you

**Comment by sajadevo** [comment]
**Hi @hall2000C**,

Please uninstall the githut-react-btn and also remove it's import module from `examples/Configurator`.

**Regards,**
**Sajad**

**Comment by kristiandelay** [comment]
adding the package fixed the issue for me without modifying any code.

`yarn add react-github-btn `

**Comment by sajadevo** [comment]
This issue is fixed on v4.0.1
