### ISSUE TITLE
[Bug] Chart is not loading properly

### ISSUE THREAD

**Issue by vishaltadha** [creativetimofficial/ct-soft-ui-dashboard-pro-react#27]
### Version
4.0.0
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro-react/#/dashboards/default
### Operating System
Mac
### Device
Macbook air
### Browser & Version
Chrome 106.0.5249.103
### Steps to reproduce
1. Go to https://demos.creative-tim.com/soft-ui-dashboard-pro-react/#/dashboards/default
2. Go to Sales Overview section on the page.
3. Notice the chart. It is not loading properly.
### What is expected?
Chart should load properly.
### What is actually happening?
Chart should load properly. Its not loading by default. On resizing window it is loading properly.

---

**Comment by sajadevo** [comment]
Hi @vishaltadha,

Thanks for using our product and reporting this issue I'll fix that on the next update of the product.

Regards,
Sajad

**Comment by tjabdoullah** [comment]
Hello, is this fixed?

**Comment by sajadevo** [comment]
@tjabdoullah not yet since it's not a major bug that breaks the entire app we'll try to update it ASAP and migrate to Apex Chart.

Cheers,
Sajad

**Comment by sajadevo** [comment]
This issue is fixed on v4.0.1
