### ISSUE TITLE
add new page without sidenav

### ISSUE THREAD

**Issue by zaferhuzmeli** [creativetimofficial/ct-soft-ui-dashboard-pro-react#28]
Hello I have this problem when compiling :

a new layout without adding to sidebar routing.

I would like to add new page but I don't want to add to sidebar, But when I try to add new route automatically redirecting to HomePage.

What should I do?

Thank you

**Comment by sajadevo** [comment]
Hey @zaferhuzmeli,

Thanks for using our product, for adding a new route first you should add it to the routes.js file so that React Router Dom can read your new route.

Regards,
Sajad

**Comment by zaferhuzmeli** [comment]
Hi @sajadevo,

Yeah I added but the problem is, when I added it automatically appear in sidenav list. 

I don't want to use it in sidebar nav. 

What should I do?

Thank you

**Comment by sajadevo** [comment]
@zaferhuzmeli, 

Then don't add it on the routes.js file just add it where the <Router /> component used for putting the routes you can do that on the app.js file.
