### ISSUE TITLE
@material/lab package problem

### ISSUE THREAD

**Issue by zaferhuzmeli** [creativetimofficial/ct-soft-ui-dashboard-pro-react#29]
Hello,

I have a problem about tabs,

I couldn't add @mui/lab for this template, I'm getting some error. 

When I tried to use oldest version, some problems are continue.

 For this application, which @mui/lab version should I use? 

Regards

**Comment by zaferhuzmeli** [comment]
![image](https://user-images.githubusercontent.com/16355053/206397841-d8e0fb89-b302-4745-8316-9adb3dd590b8.png)

**Comment by sajadevo** [comment]
Hey @zaferhuzmeli,

It seems that the issue is with mui itself if you can please share your repository with me so that I can re-produce that issue.

Cheers,
Sajad

**Comment by zaferhuzmeli** [comment]
Hi @sajadevo 

I can't share the repository with you due to security vulnerability. 

I request you to repost your project with the most up-to-date version of the mui library you have used.

Best Regards
Zafer
