### ISSUE TITLE
[Bug] FormField OR SuiFuild with useForm() hooks

### ISSUE THREAD

**Issue by ScyLabs** [creativetimofficial/ct-soft-ui-dashboard-pro-react#3]
PS : I add this Issue manually because  i'm the goetbootstrap order id : #98814
You add me the react product in your website, but i don't can take an issue in your website i don't have my orderID in your website

Version
2.0.0

Operating System
MacOS 

Device
Macbook pro 16"

Browser & Version
Brave - latest

Minimal reproduction: 
https://jsfiddle.net/f6k0jab5/

Steps to reproduce

I create my form, and i install useForm hooks in it to intercept onSubmit with the correct values.
to work, useForm use handleSubmit & register.
For register() , i add register() in input ref.
But in the onSubmit() i receive {} in values.

What is expected?
Explained in steps to reproduce

What is actually happening?
Don't receive form values with useForm

**Comment by sajadevo** [comment]
**Hi** @ScyLabs 

Thanks for using our products, its not a bug that you open it as an issue there, please use the **ISSUE_TEMPLATE.md** file on the product folder and open an issue about what you want to do and we will assist you in the best possible way.

**All the best**
**Sajad**
