### ISSUE TITLE
Scroll position automatically changed when switch between Tab

### ISSUE THREAD

**Issue by zaferhuzmeli** [creativetimofficial/ct-soft-ui-dashboard-pro-react#30]
Hi,

Again me.

I have a problem about using MUI Tabs.

Automatically page scrolls to top when switching between some tabs.

Did you faced with this problem?

Best Regards

**Comment by sajadevo** [comment]
Hey @zaferhuzmeli,

Thanks for using our product, could you please share a short video of that issue this will help me you give you better assistance.

Regards,
Sajad
