### ISSUE TITLE
Style/theme missing?

### ISSUE THREAD

**Issue by barrychapman** [creativetimofficial/ct-soft-ui-dashboard-pro-react#31]
when building buttons and importing them, it appears that all the theme styles are missing? Do we really have to do all the styling manually by ourselves?

**Comment by sajadevo** [comment]
Hey @barrychapman,

Thanks for using our product, could you please tell me the steps you've did I need to make it clear that you did the right way of importing components from the product.

Cheers,
Sajad

**Comment by barrychapman** [comment]
One of the things I have noticed is that there is no way to change the ripple effect color - is there a way to do that? I am just trying to figure out how to style all the elements to our liking

**Comment by sajadevo** [comment]
@barrychapman the ripple effect is coming from MUI and it's color is not customisable.
