### ISSUE TITLE
Can I use template with tsx?

### ISSUE THREAD

**Issue by lucianobianchidf** [creativetimofficial/ct-soft-ui-dashboard-pro-react#32]
Hi guys,

is it possible to use the template with tsx?

I have the following error when importing the template into an existing project:
**Type '{ children: string; variant: string; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<any>'.**

Attached sample code,
best regards.

![image](https://user-images.githubusercontent.com/20172896/213264885-6d95a0d1-5361-432f-af9e-c2ae90d74fa0.png)

**Comment by sajadevo** [comment]
Hey @lucianobianchidf this template is not compatible with TypeScript.
