### ISSUE TITLE
RUN npm install immediate errors for react 18 for @asseinfo/react-kanban@2.2.0

### ISSUE THREAD

**Issue by murffious** [creativetimofficial/ct-soft-ui-dashboard-pro-react#33]
RUN npm install immediate errors for react 18 for @asseinfo/react-kanban@2.2.0
soft-ui-dashboard-pro-react-v4.0.0 --> 
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree

'Log files:
/Users/morf/.npm/_logs/2023-01-21T03_44_33_932Z-debug-0.log

# npm resolution error report

While resolving: soft-ui-dashboard-pro-react@4.0.0
Found: react@18.2.0
node_modules/react
  react@"18.2.0" from the root project

Could not resolve dependency:
peer react@"^16.8.0 || ^17.0.0" from @asseinfo/react-kanban@2.2.0
node_modules/@asseinfo/react-kanban
  @asseinfo/react-kanban@"2.2.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by murffious** [comment]
solutions: recommend using DND KIT

**Comment by murffious** [comment]
AFTER deleting all references to the kanban stuff more issues came up 
the 4.0 says it fixed peer deps issues but not even close did it do that 

 "react-chartjs-2": "^5.0.0",
"chart.js": "4.2.0",

**Comment by sajadevo** [comment]
@murffious please run `npm i --legacy-peer-deps` this will fix the entire issues.

**Comment by sajadevo** [comment]
This issue is fixed on v4.0.1
