### ISSUE TITLE
Page reload return 404

### ISSUE THREAD

**Issue by zaferhuzmeli** [creativetimofficial/ct-soft-ui-dashboard-pro-react#35]
Hi,

After my teammates get the build, when they refresh or redirect other pages of the project except for some index page, it gives 404 error.

Can you provide guidance on this issue?

**Comment by sajadevo** [comment]
Hey @zaferhuzmeli,

Please change the `<BrowserRouter />` to `<HashRouter />` this will fix the issue.

Regards,
Sajad
