### ISSUE TITLE
Re-render Problem When Scrolling

### ISSUE THREAD

**Issue by dogncankrkc** [creativetimofficial/ct-soft-ui-dashboard-pro-react#36]
Hello,

I have been struggling with this problem for two days. The problem is causes to re-render when i am scrolling. I will attached the link below which is contain the screen record. You can see in the console that text is increases when the component re-render.

Can anyone help ? 
Thank you,

https://dosya.co/8o3v2c8dnas3/Screencast_from_02-03-2023_14:12:07.webm.html

**Comment by sajadevo** [comment]
The link you've shared is not working please upload the video directly to github.
