### ISSUE TITLE
home page not rendering icons correctly at start, but reloads all icons after hitting refresh

### ISSUE THREAD

**Issue by saadyacu** [creativetimofficial/ct-soft-ui-dashboard-pro-react#37]
![ScreenShot_1](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro-react/assets/647084/fde17a22-21c5-4303-b6a4-2314736eeced)

![Screenshot 2023-06-09 074706](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro-react/assets/647084/b303187a-aa03-4e3a-a338-474ab5ca9d8d)

the issue is as follow, after building the application and running it, the home page comes up, some of the icons on the home page are not intelligible (screenshot 1). Once you hit refresh, all the icons loads properly...

This is for react version, it happens on a windows 11 desktop and a mac machine

**Comment by sajadevo** [comment]
Hey there, 

This is because of the network issue sometimes since the icons needs some loading time.

Regards,
Sajad
